name: Build Docker Image
on:
  push:
    branches:
      - main
jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: login to docker hub
          id: docker-hub
          env:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_PASSWORD}}
          run: |
            docker login -u $username -p $password 
        - name: build the docker image
          id: build-docker-image
          run: |
            ls -la 
            docker build --platform=linux/amd64 -t agentvoiceresponse/avr-asr-google-cloud-speech:latest -t agentvoiceresponse/avr-asr-google-cloud-speech:${npm_package_version} .
        - name: push the docker image
          id: push-docker-image
          run: docker push agentvoiceresponse/avr-asr-google-cloud-speech:latest && docker push agentvoiceresponse/avr-asr-google-cloud-speech:${npm_package_version}
